Добавление строк/файлов для работы с Owasp

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,3 +39,30 @@ jobs:
       run: |
         ssh -o StrictHostKeyChecking=no ubuntu@56.228.0.252 'DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} bash -s' < deploy-script.sh
 
+
+    - name: OWASP ZAP Scan
+      run: |
+        sleep 120
+        
+        docker run --rm \
+          -v $(pwd):/zap/wrk:rw \
+          -t owasp/zap2docker-stable:latest \
+          zap-baseline.py \
+          -t https://artisansnook.pp.ua/ \
+          -g gen.conf \
+          -r zap-report.html \
+          -J zap-report.json
+        
+        # Проверяем статус выполнения (2 = критические уязвимости)
+        if [ $? -eq 2 ]; then
+          echo "Critical vulnerabilities found! Failing pipeline..."
+          exit 1
+        fi
+
+    - name: Upload ZAP Report
+      uses: actions/upload-artifact@v3
+      with:
+        name: zap-security-reports
+        path: |
+          zap-report.html
+          zap-report.json
